apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-postgres-migrations-volume-claim
  labels:
    app: hello-postgres-migrations
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
