apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-postgres-migrations-secret
  labels:
    app: hello-postgres-migrations
data:
  POSTGRES_HOST: hello-postgres.default
  POSTGRES_PORT: "5432"
  POSTGRES_DB: hello-db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
