apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-postgres-migrations-volume
  labels:
    type: local
    app: hello-postgres-migrations
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/dan/Developer/templates/go-template/service/hello/internal/db/postgres/migrations"
