apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-postgres-volume-claim
  labels:
    app: hello-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi