apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-postgres-secret
  labels:
    app: hello-postgres
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: hello-db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password