apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-postgres-volume
  labels:
    type: local
    app: hello-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql